export {
	createMotionPlan,
	encodeMotionPlan,
	hasBlockingMotionIssues,
	inspectMotionFrames,
	type MotionDoctorResult,
	type MotionFormat,
	type MotionFrame,
	type MotionFrameInspection,
	type MotionInput,
	type MotionIssue,
	type MotionPlan,
	type MotionResult,
	runMotionDoctor,
} from './motion.ts';
